"$schema" = "https://conductor.build/schemas/settings.repo.schema.json"

[scripts]
setup = "make setup-porting setup-nes"
run_mode = "concurrent"

[scripts.run.build-c64]
command = "make"
icon = "hammer"

[scripts.run.test-porting]
command = "make test-porting"
icon = "test-tube"

[scripts.run.setup-nes]
available_in = [ "local" ]
command = "make setup-nes"
icon = "gamepad-2"
