#!/usr/bin/env python3
"""Generate the fixed-position DHGR new-game confirmation prompt."""

from __future__ import annotations

import argparse
from pathlib import Path


PROMPT = "ARE YOU SURE [Y/N]?"
PROMPT_LEFT = 273
PROMPT_TOP = 176
SIGNALS_PER_COLUMN = 2
CHARACTER_ADVANCE = 8
FONT = {
    " ": ("000", "000", "000", "000", "000"),
    "/": ("001", "001", "010", "100", "100"),
    "?": ("110", "001", "010", "000", "010"),
    "A": ("010", "101", "111", "101", "101"),
    "E": ("111", "100", "110", "100", "111"),
    "N": ("101", "111", "111", "111", "101"),
    "O": ("111", "101", "101", "101", "111"),
    "R": ("110", "101", "110", "101", "101"),
    "S": ("111", "100", "111", "001", "111"),
    "U": ("101", "101", "101", "101", "111"),
    "Y": ("101", "101", "010", "010", "010"),
    "[": ("110", "100", "100", "100", "110"),
    "]": ("011", "001", "001", "001", "011"),
}
PROMPT_ROWS = 5
PROMPT_RIGHT = (
    PROMPT_LEFT
    + (len(PROMPT) - 1) * CHARACTER_ADVANCE
    + 3 * SIGNALS_PER_COLUMN
    - 1
)


def hgr_address(y: int) -> int:
    return 0x2000 + ((y & 0x07) << 10) + (((y >> 3) & 0x07) << 7) + (y >> 6) * 0x28


def lit_signals(row: int) -> set[int]:
    signals: set[int] = set()
    for character_index, character in enumerate(PROMPT):
        bits = FONT[character][row]
        left = PROMPT_LEFT + character_index * CHARACTER_ADVANCE
        for column, bit in enumerate(bits):
            if bit == "0":
                continue
            for repeat in range(SIGNALS_PER_COLUMN):
                signals.add(left + column * SIGNALS_PER_COLUMN + repeat)
    return signals


def bank_offset(auxiliary: bool) -> int:
    parity = 0 if auxiliary else 1
    first_sequence = next(
        sequence
        for sequence in range(PROMPT_LEFT // 7, PROMPT_RIGHT // 7 + 1)
        if sequence & 1 == parity
    )
    return first_sequence // 2


def bank_byte_count(auxiliary: bool) -> int:
    parity = 0 if auxiliary else 1
    sequences = [
        sequence
        for sequence in range(PROMPT_LEFT // 7, PROMPT_RIGHT // 7 + 1)
        if sequence & 1 == parity
    ]
    return sequences[-1] // 2 - sequences[0] // 2 + 1


def bank_masks(auxiliary: bool) -> list[int]:
    offset = bank_offset(auxiliary)
    byte_count = bank_byte_count(auxiliary)
    masks: list[int] = []
    for row in range(PROMPT_ROWS):
        row_masks = [0] * byte_count
        for signal in lit_signals(row):
            sequence = signal // 7
            if (sequence & 1 == 0) != auxiliary:
                continue
            row_masks[sequence // 2 - offset] |= 1 << (signal % 7)
        masks.extend(row_masks)
    return masks


def format_bytes(label: str, values: list[int], columns: int = 11) -> str:
    lines = [f"{label}:"]
    for start in range(0, len(values), columns):
        chunk = values[start : start + columns]
        lines.append("    .byte " + ", ".join(f"${value:02X}" for value in chunk))
    return "\n".join(lines)


def generate_include() -> str:
    auxiliary_bytes = bank_byte_count(True)
    main_bytes = bank_byte_count(False)
    if auxiliary_bytes != main_bytes:
        raise ValueError("footer prompt must span the same byte count in both banks")
    addresses = [hgr_address(PROMPT_TOP + row) for row in range(PROMPT_ROWS)]
    sections = [
        "; Generated by scripts/generate_footer_prompt.py. Do not edit.",
        f"FOOTER_PROMPT_ROWS = {PROMPT_ROWS}",
        f"FOOTER_PROMPT_BANK_BYTES = {auxiliary_bytes}",
        f"FOOTER_PROMPT_AUX_OFFSET = {bank_offset(True)}",
        f"FOOTER_PROMPT_MAIN_OFFSET = {bank_offset(False)}",
        "",
        format_bytes("footer_prompt_row_low", [address & 0xFF for address in addresses]),
        "",
        format_bytes("footer_prompt_row_high", [address >> 8 for address in addresses]),
        "",
        format_bytes("footer_prompt_aux_masks", bank_masks(True)),
        "",
        format_bytes("footer_prompt_main_masks", bank_masks(False)),
        "",
    ]
    return "\n".join(sections)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate_include(), encoding="ascii")


if __name__ == "__main__":
    main()
