#!/usr/bin/env python3
"""Generate fixed-position DHGR score digit tables for ca65."""

from __future__ import annotations

import argparse
from pathlib import Path


SCORE_LEFT = 18
SCORE_TOP = 43
DIGIT_COUNT = 5
DIGIT_PITCH = 4
DIGIT_COLUMNS = 3
SIGNALS_PER_COLUMN = 2
GLYPH_ROWS = (
    (7, 5, 5, 5, 7),
    (2, 6, 2, 2, 7),
    (7, 1, 7, 4, 7),
    (7, 1, 7, 1, 7),
    (5, 5, 7, 1, 1),
    (7, 4, 7, 1, 7),
    (7, 4, 7, 5, 7),
    (7, 1, 1, 1, 1),
    (7, 5, 7, 5, 7),
    (7, 5, 7, 1, 7),
)


def hgr_address(y: int) -> int:
    return 0x2000 + ((y & 0x07) << 10) + (((y >> 3) & 0x07) << 7) + (y >> 6) * 0x28


def digit_signal_left(position: int) -> int:
    return (SCORE_LEFT + position * DIGIT_PITCH) * 2


def bank_offset(position: int, auxiliary: bool) -> int:
    left = digit_signal_left(position)
    right = left + DIGIT_COLUMNS * SIGNALS_PER_COLUMN - 1
    parity = 0 if auxiliary else 1
    sequence_bytes = [
        sequence
        for sequence in range(left // 7, right // 7 + 1)
        if sequence & 1 == parity
    ]
    if sequence_bytes:
        return sequence_bytes[0] // 2
    return (left // 7 + ((parity - left // 7) & 1)) // 2


def pattern_mask(position: int, pattern: int, auxiliary: bool) -> int:
    offset = bank_offset(position, auxiliary)
    mask = 0
    for column in range(DIGIT_COLUMNS):
        if not pattern & (4 >> column):
            continue
        for repeat in range(SIGNALS_PER_COLUMN):
            signal = digit_signal_left(position) + column * SIGNALS_PER_COLUMN + repeat
            sequence = signal // 7
            if (sequence & 1 == 0) != auxiliary:
                continue
            if sequence // 2 != offset:
                raise ValueError("score digit spans multiple bytes in one DHGR bank")
            mask |= 1 << (signal % 7)
    return mask


def format_bytes(label: str, values: list[int], columns: int = 16) -> str:
    lines = [f"{label}:"]
    for start in range(0, len(values), columns):
        chunk = values[start : start + columns]
        lines.append("    .byte " + ", ".join(f"${value:02X}" for value in chunk))
    return "\n".join(lines)


def generate_include() -> str:
    row_addresses = [hgr_address(SCORE_TOP + row) for row in range(len(GLYPH_ROWS[0]) * 2)]
    glyph_rows = [row for glyph in GLYPH_ROWS for row in glyph]
    auxiliary_masks = [
        pattern_mask(position, pattern, True)
        for position in range(DIGIT_COUNT)
        for pattern in range(8)
    ]
    main_masks = [
        pattern_mask(position, pattern, False)
        for position in range(DIGIT_COUNT)
        for pattern in range(8)
    ]
    sections = [
        "; Generated by scripts/generate_score_digits.py. Do not edit.",
        f"SCORE_DIGIT_COUNT = {DIGIT_COUNT}",
        f"SCORE_GLYPH_HEIGHT = {len(GLYPH_ROWS[0])}",
        "",
        format_bytes("score_glyph_rows", glyph_rows),
        "",
        format_bytes(
            "score_aux_byte_offsets",
            [bank_offset(position, True) for position in range(DIGIT_COUNT)],
        ),
        "",
        format_bytes(
            "score_main_byte_offsets",
            [bank_offset(position, False) for position in range(DIGIT_COUNT)],
        ),
        "",
        format_bytes("score_aux_pattern_masks", auxiliary_masks, 8),
        "",
        format_bytes("score_main_pattern_masks", main_masks, 8),
        "",
        format_bytes("score_row_low", [address & 0xFF for address in row_addresses]),
        "",
        format_bytes("score_row_high", [address >> 8 for address in row_addresses]),
        "",
    ]
    return "\n".join(sections)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate_include(), encoding="ascii")


if __name__ == "__main__":
    main()
