#!/usr/bin/env python3
"""Convert full-screen C64 hi-res exclamations into packed sprite banners."""

from pathlib import Path
import sys

PHRASES = ("YAY", "WOW", "BOOM", "FIVES", "SIXIES", "AWESOME")


def pixel(bitmap: bytes, x: int, y: int) -> int:
    offset = ((y // 8) * 40 + x // 8) * 8 + (y & 7)
    return int(bool(bitmap[offset] & (0x80 >> (x & 7))))


def make_sprite_data(bitmap: bytes) -> bytes:
    points = [(x, y) for y in range(200) for x in range(320) if pixel(bitmap, x, y)]
    x0, x1 = min(x for x, _ in points), max(x for x, _ in points)
    y0, y1 = min(y for _, y in points), max(y for _, y in points)
    source_width, source_height = x1 - x0 + 1, y1 - y0 + 1
    scale = min(72 / source_width, 21 / source_height)
    width, height = round(source_width * scale), round(source_height * scale)
    left, top = (72 - width) // 2, (21 - height) // 2
    output = [[0] * 72 for _ in range(21)]

    for target_y in range(height):
        sy0 = y0 + target_y * source_height / height
        sy1 = y0 + (target_y + 1) * source_height / height
        for target_x in range(width):
            sx0 = x0 + target_x * source_width / width
            sx1 = x0 + (target_x + 1) * source_width / width
            samples = [
                pixel(bitmap, x, y)
                for y in range(int(sy0), max(int(sy0) + 1, int(sy1 + 0.999)))
                for x in range(int(sx0), max(int(sx0) + 1, int(sx1 + 0.999)))
            ]
            output[top + target_y][left + target_x] = int(sum(samples) / len(samples) >= 0.28)

    data = bytearray()
    for sprite in range(3):
        for y in range(21):
            for byte_index in range(3):
                value = 0
                start_x = sprite * 24 + byte_index * 8
                for bit in range(8):
                    value = (value << 1) | output[y][start_x + bit]
                data.append(value)
    return bytes(data)


def pack(data: bytes) -> bytes:
    output = bytearray()
    index = 0
    while index < len(data):
        end = index
        if data[index] == 0:
            while end < len(data) and data[end] == 0 and end - index < 127:
                end += 1
            output.append(0x80 | (end - index))
        else:
            while end < len(data) and data[end] != 0 and end - index < 127:
                end += 1
            output.append(end - index)
            output.extend(data[index:end])
        index = end
    return bytes(output)


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: convert-exclamations.py SOURCE_DIR OUTPUT_DIR")
    source_dir, output_dir = Path(sys.argv[1]), Path(sys.argv[2])
    packed, offsets = bytearray(), []
    for phrase in PHRASES:
        source = source_dir / f"{phrase}_bitmap.bin"
        bitmap = source.read_bytes()
        if len(bitmap) != 8000:
            raise ValueError(f"{source} must be an 8000-byte C64 bitmap")
        offsets.append(len(packed))
        packed.extend(pack(make_sprite_data(bitmap)))

    (output_dir / "exclamation_sprites.bin").write_bytes(packed)
    (output_dir / "exclamation_sprites_data.asm").write_text(
        "; Generated by scripts/convert-exclamations.py.\n"
        "* = $ccb1\nExclamationSpriteData:\n"
        "!bin \"src/assets/exclamation_sprites.bin\"\n"
        "ExclamationDataLo:\n!byte "
        + ",".join(f"<(ExclamationSpriteData + {offset})" for offset in offsets)
        + "\nExclamationDataHi:\n!byte "
        + ",".join(f">(ExclamationSpriteData + {offset})" for offset in offsets)
        + "\n",
        encoding="ascii",
    )
    print(f"packed six exclamations into {len(packed)} bytes")


if __name__ == "__main__":
    main()
