#!/usr/bin/env python3

from __future__ import annotations

import math
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "src" / "assets" / "transition_backdrop_logo.png"
OUT_INC = ROOT / "src" / "generated" / "transition_backdrop.inc"
OUT_CHARSET = ROOT / "src" / "assets" / "transition_backdrop_charset.bin"

CANVAS_W = 320
CANVAS_H = 200
LOGO_W = 304
LOGO_Y = 44
LOGO_THRESHOLD = 8

WAVE_BASE_Y = 164
WAVE_AMP = 10
WAVE_PERIOD = 128
WAVE_HILITE_DEPTH = 6

BLACK = 0
BLUE = 6
LIGHT_BLUE = 14


def emit_bytes(label: str, values: list[int]) -> list[str]:
    lines = [f"{label}:"]
    for i in range(0, len(values), 16):
        chunk = values[i : i + 16]
        lines.append("!byte " + ", ".join(f"${value:02x}" for value in chunk))
    return lines


def render_logo() -> bytes:
    vf = (
        f"scale={LOGO_W}:-1:flags=lanczos,"
        f"pad={CANVAS_W}:{CANVAS_H}:(ow-iw)/2:{LOGO_Y}:black,"
        "format=gray"
    )
    cmd = [
        "ffmpeg",
        "-v",
        "error",
        "-i",
        str(INPUT),
        "-vf",
        vf,
        "-frames:v",
        "1",
        "-f",
        "rawvideo",
        "pipe:1",
    ]
    return subprocess.check_output(cmd)


def build_layers(raw: bytes) -> list[int]:
    if len(raw) != CANVAS_W * CANVAS_H:
        raise RuntimeError(f"unexpected frame size: {len(raw)}")

    layers = [BLACK] * (CANVAS_W * CANVAS_H)

    for i, value in enumerate(raw):
        if value > LOGO_THRESHOLD:
            layers[i] = LIGHT_BLUE

    for x in range(CANVAS_W):
        y0 = WAVE_BASE_Y + round(WAVE_AMP * math.sin(2 * math.pi * x / WAVE_PERIOD))
        hilite_end = min(CANVAS_H, y0 + WAVE_HILITE_DEPTH)
        for y in range(y0, CANVAS_H):
            layers[y * CANVAS_W + x] = LIGHT_BLUE if y < hilite_end else BLUE

    return layers


def build_charset_and_maps(layers: list[int]) -> tuple[list[int], list[int], bytes]:
    empty_tile = (0,) * 8
    tile_to_index: dict[tuple[int, ...], int] = {empty_tile: 0}
    tiles: list[tuple[int, ...]] = [empty_tile]
    screen: list[int] = []
    colors: list[int] = []

    for cy in range(25):
        for cx in range(40):
            tile_rows: list[int] = []
            blue_count = 0
            light_blue_count = 0

            for py in range(8):
                byte_val = 0
                for px in range(8):
                    color = layers[(cy * 8 + py) * CANVAS_W + cx * 8 + px]
                    if color != BLACK:
                        byte_val |= 1 << (7 - px)
                    if color == BLUE:
                        blue_count += 1
                    elif color == LIGHT_BLUE:
                        light_blue_count += 1
                tile_rows.append(byte_val)

            tile = tuple(tile_rows)
            if tile not in tile_to_index:
                if len(tiles) >= 256:
                    raise RuntimeError("transition backdrop exceeds 256 chars")
                tile_to_index[tile] = len(tiles)
                tiles.append(tile)

            screen.append(tile_to_index[tile])
            if blue_count == 0 and light_blue_count == 0:
                colors.append(BLACK)
            elif light_blue_count >= blue_count:
                colors.append(LIGHT_BLUE)
            else:
                colors.append(BLUE)

    charset = bytes(row for tile in tiles for row in tile)
    return screen, colors, charset


def write_outputs(screen: list[int], colors: list[int], charset: bytes) -> None:
    OUT_INC.parent.mkdir(parents=True, exist_ok=True)
    OUT_CHARSET.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "; Generated by scripts/generate_transition_backdrop.py",
        f"; Source: {INPUT.relative_to(ROOT)}",
        "",
    ]
    lines.extend(emit_bytes("transition_backdrop_screen_data", screen))
    lines.append("")
    lines.extend(emit_bytes("transition_backdrop_color_data", colors))
    lines.append("")
    OUT_INC.write_text("\n".join(lines), encoding="ascii")
    OUT_CHARSET.write_bytes(charset)


def main() -> None:
    raw = render_logo()
    layers = build_layers(raw)
    screen, colors, charset = build_charset_and_maps(layers)
    write_outputs(screen, colors, charset)
    print(f"Wrote {OUT_INC}")
    print(f"Wrote {OUT_CHARSET}")
    print(f"Unique chars: {len(charset) // 8}")


if __name__ == "__main__":
    main()
