#!/usr/bin/env python3

"""Generate the exact Sixies piece-probability reference.

The calculation deliberately calls the portable conformance oracle instead of
maintaining a second implementation of the spawn rules.
"""

from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path
import runpy
import sys


ROOT = Path(__file__).resolve().parents[1]
ORACLE = runpy.run_path(str(ROOT / "tests/porting/validate_vectors.py"))
SPAWN = ORACLE["spawn"]

EMPTY_BOARD = [0] * 25
FIVE_ELIGIBLE_BOARD = [5] * 5 + [0] * 20
ALL_STATES = tuple(range(1, 256))
NEW_GAME_STATES = tuple(range(1, 256, 2))


def presented_piece(result: dict) -> tuple[int, ...]:
    count = result["count"]
    return tuple(result["raw_values"][:count])


def distribution(board: list[int], seeds: tuple[int, ...], singles_only: bool = False):
    counts = Counter()
    nominal_counts = Counter()
    five_rolls = 0
    for seed in seeds:
        nominal = SPAWN(board, seed, False)
        nominal_counts[nominal["count"]] += 1
        result = SPAWN(board, seed, singles_only)
        counts[presented_piece(result)] += 1
        if 5 in presented_piece(result):
            five_rolls += 1
    return counts, nominal_counts, five_rolls


def piece_name(piece: tuple[int, ...]) -> str:
    if len(piece) == 1:
        return f"Single {piece[0]}"
    return f"Double {piece[0]}-{piece[1]}"


def table(counts: Counter, total: int) -> list[str]:
    rows = [
        "| Presented piece | State count | Probability |",
        "| --- | ---: | ---: |",
    ]
    for piece in sorted(counts, key=lambda value: (len(value), value)):
        count = counts[piece]
        rows.append(
            f"| {piece_name(piece)} | {count}/{total} | {count / total:.4%} |"
        )
    rows.append(f"| **Total** | **{total}/{total}** | **100.0000%** |")
    return rows


def build_document() -> str:
    opening, opening_counts, _ = distribution(EMPTY_BOARD, NEW_GAME_STATES)
    normal, normal_counts, _ = distribution(EMPTY_BOARD, ALL_STATES)
    eligible, _, eligible_fives = distribution(FIVE_ELIGIBLE_BOARD, ALL_STATES)
    forced, _, _ = distribution(EMPTY_BOARD, ALL_STATES, singles_only=True)
    forced_eligible, _, forced_eligible_fives = distribution(
        FIVE_ELIGIBLE_BOARD, ALL_STATES, singles_only=True
    )

    lines = [
        "# Sixies Piece Probability Table",
        "",
        "This file is generated by `scripts/generate-probability-table.py` from",
        "the portable spawn oracle in `tests/porting/validate_vectors.py`. Run",
        "`make probability-table` after an intentional generator change.",
        "",
        "The RNG is deterministic and successive pieces are correlated. The tables",
        "therefore enumerate possible non-zero RNG states; they must not be read as",
        "independent rolls that can be multiplied across turns.",
        "",
        "## New-game opening piece",
        "",
        "New Game forces the timing-derived seed to a non-zero odd byte. Assuming",
        "each of the 128 odd seed states is equally likely, the first piece is:",
        "",
        *table(opening, len(NEW_GAME_STATES)),
        "",
        "The opening count split is exactly 64 singles and 64 doubles.",
        "",
        "## Normal play state-space distribution",
        "",
        "Before the board contains five value-5 dice, all 255 non-zero LFSR start",
        "states produce the following presented pieces:",
        "",
        *table(normal, len(ALL_STATES)),
        "",
        f"The nominal count split is {normal_counts[1]}/255 singles",
        f"({normal_counts[1] / 255:.4%}) and {normal_counts[2]}/255 doubles",
        f"({normal_counts[2] / 255:.4%}). No other ordered double or single value",
        "is reachable with the current LFSR and call cadence.",
        "",
        "## Five-eligible state-space distribution",
        "",
        "Once at least five value-5 dice are on the board, the extra low-nibble",
        "test changes the distribution to:",
        "",
        *table(eligible, len(ALL_STATES)),
        "",
        f"A generated 5 occurs for {eligible_fives}/255 states",
        f"({eligible_fives / 255:.4%}) overall, or {eligible_fives}/127",
        f"({eligible_fives / 127:.4%}) among nominal singles. It never occurs in a",
        "nominal double because the eligible fourth RNG byte cannot have a zero low",
        "nibble on a double-selected sequence.",
        "",
        "## Permanent singles-only mode",
        "",
        "The generator still performs its normal calls before forcing the presented",
        "piece count to one. With fewer than five value-5 dice:",
        "",
        *table(forced, len(ALL_STATES)),
        "",
        "With at least five value-5 dice:",
        "",
        *table(forced_eligible, len(ALL_STATES)),
        "",
        f"The eligible singles-only table contains {forced_eligible_fives}/255",
        f"generated 5s ({forced_eligible_fives / 255:.4%}).",
        "",
        "## Rule consequences",
        "",
        "- Ordered doubles matter because die 0 is the rotation origin.",
        "- Double 4-4 has zero probability; its second die is rerolled.",
        "- Generated 6s have zero probability; sixes only come from merging 5s.",
        "- Values and RNG calls are retained when endgame space detection forces a",
        "  nominal double to become a single.",
        "- Changing the RNG or reordering its calls changes this table and is a",
        "  gameplay behavior change requiring updated vectors and rules.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--output", type=Path)
    group.add_argument("--check", type=Path)
    args = parser.parse_args()
    document = build_document()

    if args.check:
        expected = args.check.read_text(encoding="utf-8")
        if expected != document:
            print(
                f"{args.check} is stale; run make probability-table",
                file=sys.stderr,
            )
            return 1
        print(f"PASS: {args.check} matches the spawn oracle")
        return 0

    if args.output:
        args.output.write_text(document, encoding="utf-8")
        print(f"Wrote {args.output}")
        return 0

    sys.stdout.write(document)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
