#!/usr/bin/env python3
"""Convert the RetroDNA logo PNG to hires bitmap data for the intro.

The demo's bitmap convention is background = 1-bits, ink = 0-bits, so the
logo bytes can be AND-merged over the starfield. Output is four char rows
(1280 bytes) covering bitmap lines 0-31 with the 199px logo centred, plus
one screen colour byte per char row picked from the dominant logo colour
in that 8-pixel band (hi nibble black, lo nibble ink).
"""

from collections import Counter
from pathlib import Path
import struct
import zlib

ROOT = Path(__file__).resolve().parent.parent
PNG_PATH = ROOT / "src" / "assets" / "retrodna_logo.png"
OUT_PATH = ROOT / "src" / "generated" / "logo.inc"

SCREEN_WIDTH = 320
CHAR_ROWS = 4

# C64 palette entries for the logo's colours.
C64_COLORS = {
    (255, 255, 255): 1,   # white
    (154, 210, 132): 13,  # light green
    (88, 141, 67): 5,     # green
}


def decode_png(path: Path):
    data = path.read_bytes()
    pos, idat, width, height = 8, b"", 0, 0
    while pos < len(data):
        length, kind = struct.unpack(">I4s", data[pos:pos + 8])
        if kind == b"IHDR":
            width, height, depth, ctype = struct.unpack(
                ">IIBB", data[pos + 8:pos + 18])
            if depth != 8 or ctype != 6:
                raise SystemExit("expected 8-bit RGBA PNG")
        elif kind == b"IDAT":
            idat += data[pos + 8:pos + 8 + length]
        pos += 12 + length

    raw = zlib.decompress(idat)
    stride, bpp = width * 4, 4
    rows, prev, p = [], bytearray(stride), 0
    for _ in range(height):
        filt = raw[p]
        line = bytearray(raw[p + 1:p + 1 + stride])
        p += 1 + stride
        for i in range(stride):
            a = line[i - bpp] if i >= bpp else 0
            b = prev[i]
            c = prev[i - bpp] if i >= bpp else 0
            if filt == 1:
                line[i] = (line[i] + a) & 255
            elif filt == 2:
                line[i] = (line[i] + b) & 255
            elif filt == 3:
                line[i] = (line[i] + (a + b) // 2) & 255
            elif filt == 4:
                pa, pb, pc = abs(b - c), abs(a - c), abs(a + b - 2 * c)
                pred = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                line[i] = (line[i] + pred) & 255
        rows.append(bytes(line))
        prev = line
    return width, height, rows


def nearest_c64(rgb):
    best = min(C64_COLORS, key=lambda c: sum((a - b) ** 2 for a, b in zip(c, rgb)))
    return C64_COLORS[best]


def main() -> None:
    width, height, rows = decode_png(PNG_PATH)
    if width > SCREEN_WIDTH or height > CHAR_ROWS * 8:
        raise SystemExit(f"logo too large: {width}x{height}")

    x_off = (SCREEN_WIDTH - width) // 2
    y_off = (CHAR_ROWS * 8 - height) // 2

    ink = [[False] * SCREEN_WIDTH for _ in range(CHAR_ROWS * 8)]
    band_colors = [Counter() for _ in range(CHAR_ROWS)]
    for y in range(height):
        for x in range(width):
            r, g, b, a = rows[y][x * 4:x * 4 + 4]
            if a > 128 and r + g + b > 30:
                ink[y + y_off][x + x_off] = True
                band_colors[(y + y_off) // 8][nearest_c64((r, g, b))] += 1

    # Bitmap: char row r, char column c, line l -> byte r*320 + c*8 + l.
    bitmap = bytearray(CHAR_ROWS * SCREEN_WIDTH)
    for row in range(CHAR_ROWS):
        for col in range(SCREEN_WIDTH // 8):
            for line in range(8):
                byte = 0xFF
                for bit in range(8):
                    if ink[row * 8 + line][col * 8 + bit]:
                        byte &= ~(0x80 >> bit)
                bitmap[row * SCREEN_WIDTH + col * 8 + line] = byte

    colors = [band.most_common(1)[0][0] if band else 1 for band in band_colors]

    lines = ["; Generated by scripts/generate_logo.py.",
             f"LOGO_CHAR_ROWS = {CHAR_ROWS}", "logo_bitmap:"]
    for start in range(0, len(bitmap), 16):
        row = ",".join(f"${b:02x}" for b in bitmap[start:start + 16])
        lines.append(f"    !byte {row}")
    lines.append("logo_colors:")
    lines.append("    !byte " + ",".join(f"${c:02x}" for c in colors))
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)} ({width}x{height} logo at "
          f"x={x_off}, colors={colors})")


if __name__ == "__main__":
    main()
