#!/usr/bin/env python3

from __future__ import annotations

SCREEN_WIDTH = 40
C64_SCREEN = 0x0400
C64_COLOR = 0xD800


def screen_code(ch: str) -> int:
    ch = ch.upper()
    if "A" <= ch <= "Z":
        return ord(ch) - ord("A") + 1
    if "0" <= ch <= "9":
        return ord(ch)
    if ch in " .,!?:-/+*":
        return ord(ch)
    return 32


def centered(text: str) -> list[int]:
    text = text.upper()[:SCREEN_WIDTH]
    left = (SCREEN_WIDTH - len(text)) // 2
    line = (" " * left + text).ljust(SCREEN_WIDTH)
    return [screen_code(ch) for ch in line]


crawl_text = [
    "",
    "A LONG TIME AGO IN A DEMO ROOM",
    "NOT VERY FAR AWAY",
    "",
    "THE BANGALORE WORKSPACE WOKE UP",
    "WITH A SIMPLE MISSION",
    "",
    "TAKE THE NOBounds STARWARS IDEA",
    "KEEP THE SPIRIT",
    "LEAVE THE DISK LOADER BEHIND",
    "",
    "RAISTLIN DESCRIBED THE TRICK",
    "COMPRESS TEXT AS IT RECEDES",
    "SKIP ROWS INTO THE DISTANCE",
    "AND LET THE CRAWL LOOP FOREVER",
    "",
    "THIS INTRO USES C64 SCREEN CODES",
    "A CYCLIC TEXT BUFFER",
    "NARROW ROWS NEAR THE HORIZON",
    "WARM COLORS NEAR THE CAMERA",
    "AND A SMALL BLUE REFLECTION",
    "",
    "NOBOUNDS SUPPLIES THE MOOD",
    "THE DEMOSCENE SUPPLIES THE RULES",
    "THE REST IS JUST TIMING",
    "",
    "PRESS RUN STOP IN YOUR HEAD",
    "THE CRAWL WILL KEEP GOING",
    "",
]

title_lines = [
    (1, "BANGALORE PRESENTS"),
    (2, "A NOBounds-STYLE STAR CRAWL"),
]

crawl_rows = list(range(4, 19))

# Perspective model from https://c64demo.com/star-wars-scrollers/:
# ZValue (= 1/depth) is interpolated linearly down the screen, from 0.6 at
# the horizon row to 1.0 at the nearest row. Row width scales with 1/depth,
# while the text-line lookup scales with depth itself (YLookupPos = C - K/Z),
# so lines compress together as the crawl recedes toward the horizon.
Z_FAR = 0.6
Z_NEAR = 1.0

inv_depth = [
    Z_FAR + (Z_NEAR - Z_FAR) * (row + 0.5) / len(crawl_rows)
    for row in range(len(crawl_rows))
]
depth = [1.0 / z for z in inv_depth]
row_widths = [round(SCREEN_WIDTH * z / inv_depth[-1]) for z in inv_depth]
# Scale so the two nearest rows are exactly one text line apart; farther
# rows then skip lines at the rate perspective dictates.
line_step = depth[-2] - depth[-1]
row_offsets = [round((d - depth[-1]) / line_step) for d in depth]
row_colors = [0x09, 0x09, 0x09, 0x02, 0x02, 0x02, 0x08, 0x08, 0x08, 0x0A, 0x0A, 0x0A, 0x07, 0x07, 0x01]

reflect_rows = [20, 21, 22, 23, 24]
reflect_widths = [38, 36, 34, 32, 30]
reflect_offsets = [0, 1, 2, 3, 4]
reflect_colors = [0x0E, 0x06, 0x06, 0x0B, 0x0B]

stars = [
    7, 17, 30, 44, 58, 73, 91, 108, 126, 142,
    159, 181, 204, 227, 245, 263, 286, 311, 337, 359,
    381, 409, 436, 462, 489, 515, 541, 566, 592, 618,
    644, 671, 698, 722, 747, 775, 803, 831, 858, 887,
    914, 943, 971, 33, 135, 251, 374, 493, 612, 733,
    852, 966,
]


def emit_byte_table(name: str, values: list[int]) -> None:
    print(f"{name}:")
    for idx in range(0, len(values), 16):
        chunk = ",".join(f"${value & 0xff:02x}" for value in values[idx:idx + 16])
        print(f"    !byte {chunk}")


def emit_word_table(name: str, values: list[int]) -> None:
    print(f"{name}_lo:")
    print("    !byte " + ",".join(f"<${value:04x}" for value in values))
    print(f"{name}_hi:")
    print("    !byte " + ",".join(f">${value:04x}" for value in values))


assert max(row_offsets) < len(crawl_text), "crawl span must fit inside the text loop"

print("; generated by scripts/generate_tables.py")
print(f"NUM_LINES = {len(crawl_text)}")
print(f"CRAWL_SPAN = {max(row_offsets)}")
print(f"CRAWL_ROWS = {len(crawl_rows)}")
print(f"REFLECT_ROWS = {len(reflect_rows)}")
print(f"STAR_COUNT = {len(stars)}")
print()

emit_word_table("crawl_screen_rows", [C64_SCREEN + row * SCREEN_WIDTH for row in crawl_rows])
emit_word_table("crawl_color_rows", [C64_COLOR + row * SCREEN_WIDTH for row in crawl_rows])
emit_byte_table("crawl_widths", row_widths)
emit_byte_table("crawl_starts", [(SCREEN_WIDTH - width) // 2 for width in row_widths])
emit_byte_table("crawl_offsets", row_offsets)
emit_byte_table("crawl_colors", row_colors)
print()

emit_word_table("reflect_screen_rows", [C64_SCREEN + row * SCREEN_WIDTH for row in reflect_rows])
emit_word_table("reflect_color_rows", [C64_COLOR + row * SCREEN_WIDTH for row in reflect_rows])
emit_byte_table("reflect_widths", reflect_widths)
emit_byte_table("reflect_starts", [(SCREEN_WIDTH - width) // 2 for width in reflect_widths])
emit_byte_table("reflect_offsets", reflect_offsets)
emit_byte_table("reflect_colors", reflect_colors)
print()

emit_byte_table("star_pos_lo", [(C64_SCREEN + pos) & 0xff for pos in stars])
emit_byte_table("star_pos_hi", [((C64_SCREEN + pos) >> 8) & 0xff for pos in stars])
emit_byte_table("star_color_lo", [(C64_COLOR + pos) & 0xff for pos in stars])
emit_byte_table("star_color_hi", [((C64_COLOR + pos) >> 8) & 0xff for pos in stars])
print()

for idx, (_, title) in enumerate(title_lines):
    emit_byte_table(f"title_{idx}", centered(title))
print("title_screen_lo:")
print("    !byte " + ",".join(f"<${C64_SCREEN + row * SCREEN_WIDTH:04x}" for row, _ in title_lines))
print("title_screen_hi:")
print("    !byte " + ",".join(f">${C64_SCREEN + row * SCREEN_WIDTH:04x}" for row, _ in title_lines))
print("title_color_lo:")
print("    !byte " + ",".join(f"<${C64_COLOR + row * SCREEN_WIDTH:04x}" for row, _ in title_lines))
print("title_color_hi:")
print("    !byte " + ",".join(f">${C64_COLOR + row * SCREEN_WIDTH:04x}" for row, _ in title_lines))
print("title_line_lo:")
print("    !byte " + ",".join(f"<title_{idx}" for idx in range(len(title_lines))))
print("title_line_hi:")
print("    !byte " + ",".join(f">title_{idx}" for idx in range(len(title_lines))))
print()

for idx, text in enumerate(crawl_text):
    emit_byte_table(f"crawl_line_{idx}", centered(text))
print("crawl_line_lo:")
print("    !byte " + ",".join(f"<crawl_line_{idx}" for idx in range(len(crawl_text))))
print("crawl_line_hi:")
print("    !byte " + ",".join(f">crawl_line_{idx}" for idx in range(len(crawl_text))))
