#!/usr/bin/env python3
"""Convert the supplied ship artwork into layered 48x42 C64 images."""

from pathlib import Path

from generate_logo import decode_png

ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = ROOT / "src" / "assets" / "transition_ships_reference.png"
OUTPUT_PATH = ROOT / "src" / "generated" / "transition_sprites.inc"

TIE_SOURCE_CROP = (235, 200, 470, 480)
TIE_OUTPUT_SIZE = (35, 42)
XWING_SOURCE_CROP = (785, 560, 1390, 780)
XWING_OUTPUT_SIZE = (48, 21)
COMPOSITE_WIDTH = 48
COMPOSITE_HEIGHT = 42
SPRITE_WIDTH = 24
SPRITE_HEIGHT = 21


def tie_pixel_class(r: int, g: int, b: int) -> int:
    """Return 0=space, 1=dark source detail, or 2=light hull."""
    if max(r, g, b) < 22:
        return 0
    if b > r * 1.12 and b > g * 1.12:
        return 1
    return 2


def xwing_pixel_class(r: int, g: int, b: int) -> int:
    """Return 0=space, 1=orange marking, or 2=gray hull."""
    if max(r, g, b) < 22:
        return 0
    if r > g * 1.12 and r > b * 1.12:
        return 1
    return 2


def reduce_ship(rows, source_crop, output_size, classifier):
    left, top, right, bottom = source_crop
    out_width, out_height = output_size
    crop_width = right - left
    crop_height = bottom - top
    pixels = [[0] * out_width for _ in range(out_height)]

    for out_y in range(out_height):
        iy0 = int(top + out_y * crop_height / out_height)
        iy1 = max(iy0 + 1, int(top + (out_y + 1) * crop_height
                              / out_height + 0.999))
        for out_x in range(out_width):
            ix0 = int(left + out_x * crop_width / out_width)
            ix1 = max(ix0 + 1, int(left + (out_x + 1) * crop_width
                                  / out_width + 0.999))
            counts = [0, 0, 0]
            for src_y in range(iy0, iy1):
                row = rows[src_y]
                for src_x in range(ix0, ix1):
                    offset = src_x * 4
                    r, g, b = row[offset:offset + 3]
                    counts[classifier(r, g, b)] += 1

            samples = sum(counts)
            if (counts[1] + counts[2]) * 9 < samples:
                continue
            pixels[out_y][out_x] = 1 if counts[1] > counts[2] else 2

    # Carve solid hull interiors back to black so the source outlines and
    # mechanical gaps remain readable at the reduced resolution.
    outlined = [row[:] for row in pixels]
    for y in range(1, out_height - 1):
        for x in range(1, out_width - 1):
            if pixels[y][x] != 2:
                continue
            if all(pixels[ny][nx] != 0
                   for nx, ny in ((x - 1, y), (x + 1, y),
                                  (x, y - 1), (x, y + 1))):
                outlined[y][x] = 0
    return outlined


def place_composite(ship):
    canvas = [[0] * COMPOSITE_WIDTH for _ in range(COMPOSITE_HEIGHT)]
    offset_x = (COMPOSITE_WIDTH - len(ship[0])) // 2
    offset_y = (COMPOSITE_HEIGHT - len(ship)) // 2
    for y, row in enumerate(ship):
        for x, value in enumerate(row):
            canvas[offset_y + y][offset_x + x] = value
    return canvas


def quadrant_to_sprite(canvas, quadrant_x, quadrant_y, layer):
    data = bytearray()
    origin_x = quadrant_x * SPRITE_WIDTH
    origin_y = quadrant_y * SPRITE_HEIGHT
    for y in range(SPRITE_HEIGHT):
        bits = 0
        for x in range(SPRITE_WIDTH):
            active = canvas[origin_y + y][origin_x + x] == layer
            bits = (bits << 1) | active
        data.extend(((bits >> 16) & 0xff, (bits >> 8) & 0xff, bits & 0xff))
    data.append(0)
    return data


def emit_bytes(lines, data):
    for start in range(0, len(data), 16):
        values = ",".join(f"${value:02x}" for value in data[start:start + 16])
        lines.append(f"    !byte {values}")


def main() -> None:
    width, height, rows = decode_png(SOURCE_PATH)
    ships = (
        ("tie", place_composite(reduce_ship(
            rows, TIE_SOURCE_CROP, TIE_OUTPUT_SIZE, tie_pixel_class))),
        ("xwing", place_composite(reduce_ship(
            rows, XWING_SOURCE_CROP, XWING_OUTPUT_SIZE, xwing_pixel_class))),
    )
    lines = [
        "; Generated by scripts/generate_transition_sprites.py.",
        "; TIE then X-wing, four quadrants each, detail layer then hull layer.",
        "shiptransition_sprite_data:",
    ]
    counts = []
    for ship_name, canvas in ships:
        for quadrant_y in range(2):
            for quadrant_x in range(2):
                quadrant_name = ("top" if quadrant_y == 0 else "bottom") + \
                                "-" + ("left" if quadrant_x == 0 else "right")
                for layer, layer_name in ((1, "detail"), (2, "hull")):
                    data = quadrant_to_sprite(
                        canvas, quadrant_x, quadrant_y, layer)
                    lines.append(
                        f"; {ship_name} {quadrant_name} {layer_name}")
                    emit_bytes(lines, data)
                    counts.append((ship_name, quadrant_name, layer_name,
                                   sum(byte.bit_count() for byte in data)))

    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="ascii")
    summary = ", ".join(f"{ship}-{name}-{layer}={count}px"
                        for ship, name, layer, count in counts)
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)} from {width}x{height} source "
          f"({summary})")


if __name__ == "__main__":
    main()
