#!/usr/bin/env python3
"""Convert the supplied TIE artwork into one layered 48x42 C64 image."""

from pathlib import Path

from generate_logo import decode_png

ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = ROOT / "src" / "assets" / "transition_ships_reference.png"
OUTPUT_PATH = ROOT / "src" / "generated" / "transition_sprites.inc"

SOURCE_CROP = (235, 200, 470, 480)
SOURCE_OUTPUT_SIZE = (35, 42)
COMPOSITE_WIDTH = 48
COMPOSITE_HEIGHT = 42
SPRITE_WIDTH = 24
SPRITE_HEIGHT = 21


def pixel_class(r: int, g: int, b: int) -> int:
    """Return 0=space, 1=dark source detail, or 2=light hull."""
    if max(r, g, b) < 22:
        return 0
    if b > r * 1.12 and b > g * 1.12:
        return 1
    return 2


def reduce_tie(rows):
    left, top, right, bottom = SOURCE_CROP
    out_width, out_height = SOURCE_OUTPUT_SIZE
    crop_width = right - left
    crop_height = bottom - top
    pixels = [[0] * out_width for _ in range(out_height)]

    for out_y in range(out_height):
        iy0 = int(top + out_y * crop_height / out_height)
        iy1 = max(iy0 + 1, int(top + (out_y + 1) * crop_height
                              / out_height + 0.999))
        for out_x in range(out_width):
            ix0 = int(left + out_x * crop_width / out_width)
            ix1 = max(ix0 + 1, int(left + (out_x + 1) * crop_width
                                  / out_width + 0.999))
            counts = [0, 0, 0]
            for src_y in range(iy0, iy1):
                row = rows[src_y]
                for src_x in range(ix0, ix1):
                    offset = src_x * 4
                    r, g, b = row[offset:offset + 3]
                    counts[pixel_class(r, g, b)] += 1

            samples = sum(counts)
            if (counts[1] + counts[2]) * 9 < samples:
                continue
            pixels[out_y][out_x] = 1 if counts[1] > counts[2] else 2

    # Carve solid light hull interiors back to black so the cockpit, wing
    # braces, and panel gaps remain readable at the reduced resolution.
    outlined = [row[:] for row in pixels]
    for y in range(1, out_height - 1):
        for x in range(1, out_width - 1):
            if pixels[y][x] != 2:
                continue
            if all(pixels[ny][nx] != 0
                   for nx, ny in ((x - 1, y), (x + 1, y),
                                  (x, y - 1), (x, y + 1))):
                outlined[y][x] = 0
    return outlined


def place_composite(tie):
    canvas = [[0] * COMPOSITE_WIDTH for _ in range(COMPOSITE_HEIGHT)]
    offset_x = (COMPOSITE_WIDTH - len(tie[0])) // 2
    for y, row in enumerate(tie):
        for x, value in enumerate(row):
            canvas[y][offset_x + x] = value
    return canvas


def quadrant_to_sprite(canvas, quadrant_x, quadrant_y, layer):
    data = bytearray()
    origin_x = quadrant_x * SPRITE_WIDTH
    origin_y = quadrant_y * SPRITE_HEIGHT
    for y in range(SPRITE_HEIGHT):
        bits = 0
        for x in range(SPRITE_WIDTH):
            active = canvas[origin_y + y][origin_x + x] == layer
            bits = (bits << 1) | active
        data.extend(((bits >> 16) & 0xff, (bits >> 8) & 0xff, bits & 0xff))
    data.append(0)
    return data


def emit_bytes(lines, data):
    for start in range(0, len(data), 16):
        values = ",".join(f"${value:02x}" for value in data[start:start + 16])
        lines.append(f"    !byte {values}")


def main() -> None:
    width, height, rows = decode_png(SOURCE_PATH)
    canvas = place_composite(reduce_tie(rows))
    lines = [
        "; Generated by scripts/generate_transition_sprites.py.",
        "; Four quadrants, each ordered detail layer then hull layer.",
        "shiptransition_sprite_data:",
    ]
    counts = []
    for quadrant_y in range(2):
        for quadrant_x in range(2):
            name = ("top" if quadrant_y == 0 else "bottom") + "-" + \
                   ("left" if quadrant_x == 0 else "right")
            for layer, layer_name in ((1, "detail"), (2, "hull")):
                data = quadrant_to_sprite(canvas, quadrant_x, quadrant_y, layer)
                lines.append(f"; {name} {layer_name}")
                emit_bytes(lines, data)
                counts.append((name, layer_name,
                               sum(byte.bit_count() for byte in data)))

    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="ascii")
    summary = ", ".join(f"{name}-{layer}={count}px"
                        for name, layer, count in counts)
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)} from {width}x{height} source "
          f"({summary})")


if __name__ == "__main__":
    main()
