#!/usr/bin/env python3

from __future__ import annotations

import math
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT_DIR / "src" / "generated" / "filled_sine.inc"

SUBPIX = 2
WAVE_CHAR_BASE = 64
FIELD_MID = 48
FIELD_AMP = 22


def mk8x8(yoffs: int, a: int, b: int, c: int) -> tuple[tuple[int, ...], ...]:
    rows = []
    for y in range(8):
        yy = (y + yoffs) * SUBPIX
        row = []
        for x in range(8):
            xx = x * SUBPIX
            row.append(1 if a * xx + b * yy + c >= 0 else 0)
        rows.append(tuple(row))
    return tuple(rows)


def row_to_byte(row: tuple[int, ...]) -> int:
    value = 0
    for x, bit in enumerate(row):
        if bit:
            value |= 1 << (7 - x)
    return value


def emit_bytes(label: str, values: list[int]) -> list[str]:
    lines = [f"{label}:"]
    for i in range(0, len(values), 16):
        chunk = values[i : i + 16]
        lines.append("!byte " + ", ".join(f"${value:02x}" for value in chunk))
    return lines


def main() -> None:
    empty = tuple(tuple(0 for _ in range(8)) for _ in range(8))
    full = tuple(tuple(1 for _ in range(8)) for _ in range(8))

    char_to_index: dict[tuple[tuple[int, ...], ...], int] = {empty: 0, full: 1}
    chars = [empty, full]

    lookup_top: list[int] = []
    lookup_mid: list[int] = []
    lookup_bot: list[int] = []

    for y0 in range(8 * SUBPIX):
        for dy in range(-4 * SUBPIX, 4 * SUBPIX):
            y1 = y0 + dy
            a = -(y1 - y0)
            b = 8 * SUBPIX
            c = -(a * 0 + b * y0)

            triple = []
            for yoffs in (-8, 0, 8):
                ch = mk8x8(yoffs, a, b, c)
                if ch not in char_to_index:
                    char_to_index[ch] = len(chars)
                    chars.append(ch)
                triple.append(WAVE_CHAR_BASE + char_to_index[ch])

            lookup_top.append(triple[0])
            lookup_mid.append(triple[1])
            lookup_bot.append(triple[2])

    char_bytes: list[int] = []
    for ch in chars:
        for row in ch:
            char_bytes.append(row_to_byte(row))

    sine_curve = [
        round(FIELD_MID + FIELD_AMP * math.sin(2 * math.pi * i / 64))
        for i in range(64)
    ]

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "; Generated by scripts/generate_filled_sine.py",
        "; Based on the filled-segment charset technique described by Nurpax:",
        "; https://nurpax.github.io/posts/2018-06-07-c64-filled-sinewave.html",
        "",
        f"wave_char_count = {len(chars)}",
        f"wave_char_pages = {len(char_bytes) // 256}",
        f"wave_char_tail = {len(char_bytes) % 256}",
        "",
    ]
    lines.extend(emit_bytes("wave_lookup_top", lookup_top))
    lines.append("")
    lines.extend(emit_bytes("wave_lookup_mid", lookup_mid))
    lines.append("")
    lines.extend(emit_bytes("wave_lookup_bot", lookup_bot))
    lines.append("")
    lines.extend(emit_bytes("sine_curve", sine_curve))
    lines.append("")
    lines.extend(emit_bytes("wave_charset", char_bytes))
    lines.append("")

    OUT_PATH.write_text("\n".join(lines), encoding="ascii")

    print(f"Wrote {OUT_PATH}")
    print(f"Unique chars: {len(chars)}")


if __name__ == "__main__":
    main()
