#!/usr/bin/env python3
"""Generate the five-sprite STARWARS crawl title.

Only the STARWARS logo glyphs are retained from shadowyblade's Star Wars
font. The attached OTF is not vendored; these 14x14 monochrome rows are the
locally rasterized title needed by the C64 sprite layer.
"""

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "generated" / "starwars_title.inc"

GLYPHS = {
    "A": (
        "00000111100000", "00001111100000", "00001111100000", "00001111100000",
        "00011101110000", "00011100110000", "00111100111000", "00111000111000",
        "00111111111100", "00111111111100", "00111111111100", "01111111111100",
        "11100000001110", "11100000001110",
    ),
    "R": (
        "11111110000000", "11111110000000", "11111111000000", "11111111100000",
        "11100011100000", "11100011100000", "11111111000000", "11111111000000",
        "11111110000000", "11111110000000", "11101110000000", "11101111111110",
        "11100111111110", "11100011111110",
    ),
    "S": (
        "00000011111111", "00000011111111", "00000111111111", "00000111111111",
        "00000110000000", "00000111000000", "00000011100000", "00000011100000",
        "00000001110000", "00000000110000", "00000000110000", "11111111110000",
        "11111111100000", "11111111100000",
    ),
    "T": (
        "00111111111100", "00111111111100", "00111111111100", "00111111111100",
        "00000011000000", "00000011000000", "00000011000000", "00000011000000",
        "00000011000000", "00000011000000", "00000011000000", "00000011000000",
        "00000011000000", "00000011000000",
    ),
    "W": (
        "11100111000110", "11100111001110", "11100111001110", "11100111001110",
        "01110111111100", "00110111111100", "00111111111100", "00111111111000",
        "00111111111000", "00011101110000", "00011101110000", "00011101110000",
        "00001100100000", "00001100100000",
    ),
}


def build_sprite_data() -> bytes:
    width, height = 120, 21
    canvas = [[0] * width for _ in range(height)]
    for index, character in enumerate("STARWARS"):
        origin_x = index * 15
        for y, row in enumerate(GLYPHS[character]):
            for x, bit in enumerate(row):
                if bit == "1":
                    canvas[y + 3][origin_x + x] = 1

    output = bytearray()
    for sprite in range(5):
        for y in range(height):
            value = 0
            for x in range(24):
                value = (value << 1) | canvas[y][sprite * 24 + x]
            output.extend((value >> 16, (value >> 8) & 0xFF, value & 0xFF))
        output.append(0)
    assert len(output) == 5 * 64
    return bytes(output)


def main() -> None:
    data = build_sprite_data()
    lines = [
        "; Generated by scripts/generate_starwars_title.py.",
        "starwars_title_sprite_data:",
    ]
    for offset in range(0, len(data), 16):
        lines.append("    !byte " + ",".join(
            f"${value:02x}" for value in data[offset:offset + 16]))
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(data)} bytes / 5 sprites)")


if __name__ == "__main__":
    main()
