#!/usr/bin/env python3
"""Generate PAL SID frequency lookup tables for MIDI notes 0-127."""

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "generated" / "sid_pal_freq.inc"
PAL_CLOCK = 985_248


def sid_frequency(midi_note: int) -> int:
    hz = 440.0 * 2 ** ((midi_note - 69) / 12)
    return min(0xFFFF, round(hz * (1 << 24) / PAL_CLOCK))


def emit_table(name: str, values: list[int]) -> list[str]:
    lines = [f"{name}:"]
    for start in range(0, len(values), 16):
        row = ",".join(f"${value:02x}" for value in values[start : start + 16])
        lines.append(f"    !byte {row}")
    return lines


def main() -> None:
    frequencies = [sid_frequency(note) for note in range(128)]
    lines = ["; Generated by scripts/generate_sid_frequency_table.py."]
    lines += emit_table("sid_freq_lo", [value & 0xFF for value in frequencies])
    lines += emit_table("sid_freq_hi", [value >> 8 for value in frequencies])
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
