#!/usr/bin/env python3

import pathlib
import sys


BANDS = 5
BITMAP_BAND_SIZE = 1600
COLOR_BAND_SIZE = 200


def pack(data):
    output = bytearray()
    index = 0
    while index < len(data):
        run = 1
        while (
            index + run < len(data)
            and data[index + run] == data[index]
            and run < 127
        ):
            run += 1
        if run >= 3:
            output.extend((0x80 | run, data[index]))
            index += run
            continue

        literal_start = index
        index += run
        while index < len(data) and index - literal_start < 127:
            next_run = 1
            while (
                index + next_run < len(data)
                and data[index + next_run] == data[index]
                and next_run < 127
            ):
                next_run += 1
            if next_run >= 3:
                break
            index += min(next_run, 127 - (index - literal_start))
        literal = data[literal_start:index]
        output.append(len(literal))
        output.extend(literal)

    output.append(0)
    return output


def unpack(data):
    output = bytearray()
    index = 0
    while data[index]:
        token = data[index]
        index += 1
        if token & 0x80:
            output.extend((data[index],) * (token & 0x7f))
            index += 1
        else:
            output.extend(data[index:index + token])
            index += token
    return output


def pointer_table(name, offsets):
    low = ",".join(f"<(GameOverKoalaPacked + {offset})" for offset in offsets)
    high = ",".join(f">(GameOverKoalaPacked + {offset})" for offset in offsets)
    return f"{name}Lo:\n!byte {low}\n{name}Hi:\n!byte {high}\n"


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: pack-koala.py INPUT.kla OUTPUT_DIRECTORY")

    source = pathlib.Path(sys.argv[1])
    output_directory = pathlib.Path(sys.argv[2])
    koala = source.read_bytes()
    if len(koala) != 10003 or koala[:2] != bytes((0x00, 0x60)):
        raise ValueError("expected a standard 10003-byte Koala file loaded at $6000")

    bitmap = koala[2:8002]
    screen = koala[8002:9002]
    color = koala[9002:10002]
    background = koala[10002]
    packed = bytearray()
    bitmap_offsets = []
    screen_offsets = []
    color_offsets = []

    for band in range(BANDS):
        bitmap_offsets.append(len(packed))
        start = band * BITMAP_BAND_SIZE
        bitmap_band = bitmap[start:start + BITMAP_BAND_SIZE]
        packed_bitmap = pack(bitmap_band)
        assert unpack(packed_bitmap) == bitmap_band
        packed.extend(packed_bitmap)

        screen_offsets.append(len(packed))
        start = band * COLOR_BAND_SIZE
        screen_band = screen[start:start + COLOR_BAND_SIZE]
        packed_screen = pack(screen_band)
        assert unpack(packed_screen) == screen_band
        packed.extend(packed_screen)

        color_offsets.append(len(packed))
        color_band = color[start:start + COLOR_BAND_SIZE]
        packed_color = pack(color_band)
        assert unpack(packed_color) == color_band
        packed.extend(packed_color)

    output_directory.mkdir(parents=True, exist_ok=True)
    (output_directory / "game_over_koala_packed.bin").write_bytes(packed)
    tables = "; Generated by scripts/pack-koala.py.\n"
    tables += pointer_table("GameOverKoalaBitmap", bitmap_offsets)
    tables += pointer_table("GameOverKoalaScreen", screen_offsets)
    tables += pointer_table("GameOverKoalaColor", color_offsets)
    tables += f"GameOverKoalaBackground = ${background:02x}\n"
    (output_directory / "game_over_koala_tables.asm").write_text(tables, encoding="ascii")
    print(f"Packed {len(bitmap) + len(screen) + len(color)} bytes into {len(packed)} bytes")


if __name__ == "__main__":
    main()
