#!/usr/bin/env python3

"""Pack the gameplay sidebar logo into the two safe gaps reserved for it."""

import pathlib
import sys


BITMAP_ROW_BYTES = 80
SCREEN_ROW_BYTES = 10
ROWS = 4


def pack(data):
    output = bytearray()
    index = 0
    while index < len(data):
        run = 1
        while index + run < len(data) and data[index + run] == data[index] and run < 127:
            run += 1
        if run >= 3:
            output.extend((0x80 | run, data[index]))
            index += run
            continue

        literal_start = index
        index += run
        while index < len(data) and index - literal_start < 127:
            next_run = 1
            while (
                index + next_run < len(data)
                and data[index + next_run] == data[index]
                and next_run < 127
            ):
                next_run += 1
            if next_run >= 3:
                break
            index += min(next_run, 127 - (index - literal_start))
        literal = data[literal_start:index]
        output.append(len(literal))
        output.extend(literal)
    output.append(0)
    return output


def emit_bytes(data):
    lines = []
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        lines.append("!byte " + ",".join(f"${value:02x}" for value in chunk))
    return "\n".join(lines)


def main():
    if len(sys.argv) != 4:
        raise SystemExit("usage: pack-sidebar-logo.py BITMAP.bin SCREEN.bin OUTPUT.asm")

    bitmap = pathlib.Path(sys.argv[1]).read_bytes()
    screen = pathlib.Path(sys.argv[2]).read_bytes()
    if len(bitmap) != BITMAP_ROW_BYTES * ROWS or len(screen) != SCREEN_ROW_BYTES * ROWS:
        raise ValueError("expected an 80x32 hi-res logo")

    bitmap_rows = [
        pack(bitmap[row * BITMAP_ROW_BYTES:(row + 1) * BITMAP_ROW_BYTES])
        for row in range(ROWS)
    ]
    screen_rows = [
        pack(screen[row * SCREEN_ROW_BYTES:(row + 1) * SCREEN_ROW_BYTES])
        for row in range(ROWS)
    ]

    # Row 3 and the color rows fit below the title data. Rows 0-2 fit below
    # screen RAM. Keeping both regions bounded protects runtime sprite memory.
    sections = ["; Generated by scripts/pack-sidebar-logo.py.", "* = $2f7f"]
    sections.extend(("SidebarLogoBitmapRow3:", emit_bytes(bitmap_rows[3])))
    for row, packed in enumerate(screen_rows):
        sections.extend((f"SidebarLogoScreenRow{row}:", emit_bytes(packed)))
    sections.append("* = $4319")
    for row in range(3):
        sections.extend((f"SidebarLogoBitmapRow{row}:", emit_bytes(bitmap_rows[row])))

    output = pathlib.Path(sys.argv[3])
    output.write_text("\n".join(sections) + "\n", encoding="ascii")
    print(
        f"Packed {len(bitmap) + len(screen)} logo bytes into "
        f"{sum(map(len, bitmap_rows + screen_rows))} bytes"
    )


if __name__ == "__main__":
    main()
