#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

SJASM_VERSION="${SJASM_VERSION:-v1.24.0}"
SJASM_SRC_DIR="$ROOT_DIR/.tools/src/sjasmplus-$SJASM_VERSION"
SJASM_PREFIX="$ROOT_DIR/.tools/sjasmplus"
SJASM_BIN="$SJASM_PREFIX/bin/sjasmplus"
CONTEXT_DIR="$ROOT_DIR/.context"
ENV_FILE="$CONTEXT_DIR/vz200-env.sh"

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Required command not found: $1" >&2
    exit 1
  fi
}

install_sjasmplus() {
  if [[ -x "$SJASM_BIN" ]]; then
    echo "Workspace-local sjasmplus already available at $SJASM_BIN"
    "$SJASM_BIN" --version
    return
  fi

  need_cmd git
  need_cmd cmake
  need_cmd make
  need_cmd clang

  mkdir -p "$(dirname "$SJASM_SRC_DIR")"
  rm -rf "$SJASM_SRC_DIR"

  git clone --depth 1 --branch "$SJASM_VERSION" --recursive \
    https://github.com/z00m128/sjasmplus.git "$SJASM_SRC_DIR"

  cmake -S "$SJASM_SRC_DIR" -B "$SJASM_SRC_DIR/build" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$SJASM_PREFIX"
  cmake --build "$SJASM_SRC_DIR/build" --parallel
  cmake --install "$SJASM_SRC_DIR/build"

  echo "Workspace-local sjasmplus ready at $SJASM_BIN"
  "$SJASM_BIN" --version
}

install_mame() {
  if command -v mame >/dev/null 2>&1; then
    echo "MAME already available at $(command -v mame)"
    mame -help | sed -n '1,3p'
    return
  fi

  need_cmd brew
  brew install mame
  mame -help | sed -n '1,3p'
}

install_ffmpeg() {
  if command -v ffmpeg >/dev/null 2>&1; then
    echo "ffmpeg already available at $(command -v ffmpeg)"
    return
  fi

  need_cmd brew
  brew install ffmpeg
}

write_env_file() {
  mkdir -p "$CONTEXT_DIR"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-vz200-dev.sh
export SIXIES_VZ200_ROOT="$ROOT_DIR"
export SIXIES_VZ200_SJASMPLUS="$SJASM_BIN"
export PATH="$SJASM_PREFIX/bin:\$PATH"
EOF
  echo "Wrote $ENV_FILE"
}

install_sjasmplus
install_mame
install_ffmpeg
write_env_file

echo "VZ200 development environment is ready."
echo "Source $ENV_FILE to add sjasmplus to PATH in a shell."
