#!/usr/bin/env bash
set -euo pipefail

# Bootstrap a fresh branch/worktree without depending on its absolute path.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FALLBACK_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(git -C "$FALLBACK_ROOT" rev-parse --show-toplevel 2>/dev/null || printf '%s' "$FALLBACK_ROOT")"
CONTEXT_DIR="$ROOT_DIR/.context"
PATHS_FILE="$CONTEXT_DIR/porting-paths.env"
MANIFEST_FILE="$CONTEXT_DIR/porting-manifest.txt"

cd "$ROOT_DIR"

required_files=(
  "AGENTS.md"
  "README.md"
  "Makefile"
  "docs/game-rules.md"
  "docs/porting-gameboy.md"
  "docs/porting-nes.md"
  "docs/reference-assets.md"
  "docs/reference/gameplay-valid-target.png"
  "docs/reference/gameplay-invalid-target.png"
  "tests/porting/gameplay-vectors.json"
  "tests/porting/validate_vectors.py"
  "src/grid_base.asm"
  "src/assets/Studio313.kla"
  "src/assets/title_logo_flat_master.png"
  "src/assets/game_over_logo_flat_master.png"
  "src/assets/main_mascot_master.png"
  "src/assets/settings_dice_master.png"
  "src/assets/credits_logo_master.jpg"
  "src/assets/credits_mascot_master.png"
  "src/assets/font/SixiesFont_sheet.png"
  "src/assets/die_one.asm"
  "src/assets/die_two.asm"
  "src/assets/die_three.asm"
  "src/assets/die_four.asm"
  "src/assets/die_five.asm"
  "src/assets/die_six.asm"
)

required_directories=(
  "src/assets/exclamations"
  "src/music"
  "scripts"
  "tests/porting"
)

missing=0
for path in "${required_files[@]}"; do
  if [[ ! -f "$ROOT_DIR/$path" ]]; then
    printf 'Missing required file: %s\n' "$path" >&2
    missing=1
  fi
done
for path in "${required_directories[@]}"; do
  if [[ ! -d "$ROOT_DIR/$path" ]]; then
    printf 'Missing required directory: %s\n' "$path" >&2
    missing=1
  fi
done
if [[ "$missing" -ne 0 ]]; then
  echo "Porting workspace setup failed. Check out the complete Sixies branch." >&2
  exit 1
fi

command -v python3 >/dev/null 2>&1 || {
  echo "python3 is required to validate the gameplay contract." >&2
  exit 1
}
command -v make >/dev/null 2>&1 || {
  echo "make is required to run repository setup and validation." >&2
  exit 1
}

mkdir -p "$CONTEXT_DIR"

write_export() {
  printf 'export %s=%q\n' "$1" "$2"
}

{
  echo "# Generated by scripts/setup-porting-workspace.sh"
  write_export SIXIES_REPO_ROOT "$ROOT_DIR"
  write_export SIXIES_AGENTS "$ROOT_DIR/AGENTS.md"
  write_export SIXIES_GAME_RULES "$ROOT_DIR/docs/game-rules.md"
  write_export SIXIES_GAMEBOY_PLAN "$ROOT_DIR/docs/porting-gameboy.md"
  write_export SIXIES_NES_PLAN "$ROOT_DIR/docs/porting-nes.md"
  write_export SIXIES_TEST_VECTORS "$ROOT_DIR/tests/porting/gameplay-vectors.json"
  write_export SIXIES_REFERENCE_INDEX "$ROOT_DIR/docs/reference-assets.md"
  write_export SIXIES_REFERENCE_ROOT "$ROOT_DIR/docs/reference"
  write_export SIXIES_ASSET_ROOT "$ROOT_DIR/src/assets"
  write_export SIXIES_C64_SOURCE "$ROOT_DIR/src/grid_base.asm"
  write_export SIXIES_C64_PRG "$ROOT_DIR/build/dice_merge.prg"
} > "$PATHS_FILE"

branch="$(git branch --show-current 2>/dev/null || true)"
{
  printf 'Sixies workspace: %s\n' "$ROOT_DIR"
  printf 'Branch: %s\n' "${branch:-detached HEAD}"
  printf 'Agent guide: %s\n' "$ROOT_DIR/AGENTS.md"
  printf 'Rules: %s\n' "$ROOT_DIR/docs/game-rules.md"
  printf 'Game Boy plan: %s\n' "$ROOT_DIR/docs/porting-gameboy.md"
  printf 'NES plan: %s\n' "$ROOT_DIR/docs/porting-nes.md"
  printf 'Test vectors: %s\n' "$ROOT_DIR/tests/porting/gameplay-vectors.json"
  printf 'Artwork index: %s\n' "$ROOT_DIR/docs/reference-assets.md"
  printf 'Source assets: %s\n' "$ROOT_DIR/src/assets"
  printf 'Generated path exports: %s\n' "$PATHS_FILE"
} > "$MANIFEST_FILE"

make test-porting

c64_status="not built (ACME unavailable)"
if [[ -x "$ROOT_DIR/.tools/acme/bin/acme" ]] || command -v acme >/dev/null 2>&1; then
  make setup-acme
  make
  c64_status="built at $ROOT_DIR/build/dice_merge.prg"
fi

cat "$MANIFEST_FILE"
printf 'C64 baseline: %s\n' "$c64_status"
echo "Setup complete. Source $PATHS_FILE to load canonical paths in a shell."
