#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FALLBACK_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(git -C "$FALLBACK_ROOT" rev-parse --show-toplevel 2>/dev/null || printf '%s' "$FALLBACK_ROOT")"
CONTEXT_DIR="$ROOT_DIR/.context"
PORT_ROOT="$ROOT_DIR/ports/nes"
ENV_FILE="$CONTEXT_DIR/nes-toolchain.env"
STATUS_FILE="$CONTEXT_DIR/nes-toolchain.txt"

cd "$ROOT_DIR"

if ! command -v cc65 >/dev/null 2>&1; then
  if command -v brew >/dev/null 2>&1; then
    echo "cc65 not found on PATH. Installing via Homebrew..."
    brew install cc65
  else
    echo "cc65 is required for NES development and Homebrew is unavailable." >&2
    exit 1
  fi
fi

if ! command -v nestopia >/dev/null 2>&1; then
  if command -v brew >/dev/null 2>&1; then
    echo "Nestopia UE not found on PATH. Installing via Homebrew..."
    brew install nestopia-ue
  else
    echo "Nestopia UE is required for NES ROM smoke tests and Homebrew is unavailable." >&2
    exit 1
  fi
fi

required_tools=(cc65 ca65 ld65 cl65 ar65 od65 sim65)
for tool in "${required_tools[@]}"; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    printf 'Missing required NES tool: %s\n' "$tool" >&2
    exit 1
  fi
done

mkdir -p "$CONTEXT_DIR" "$PORT_ROOT"/{build,cfg,include,src,tests}

write_export() {
  printf 'export %s=%q\n' "$1" "$2"
}

cc65_version="$(cc65 --version 2>&1 | head -n 1 || true)"

{
  echo "# Generated by scripts/setup-nes-toolchain.sh"
  write_export SIXIES_NES_PORT_ROOT "$PORT_ROOT"
  write_export SIXIES_NES_BUILD_ROOT "$PORT_ROOT/build"
  write_export SIXIES_NES_CFG_ROOT "$PORT_ROOT/cfg"
  write_export SIXIES_NES_INCLUDE_ROOT "$PORT_ROOT/include"
  write_export SIXIES_NES_SRC_ROOT "$PORT_ROOT/src"
  write_export SIXIES_NES_TEST_ROOT "$PORT_ROOT/tests"
  write_export SIXIES_NES_PLAN "$ROOT_DIR/docs/porting-nes.md"
  write_export SIXIES_CC65_VERSION "${cc65_version:-unknown}"
  write_export SIXIES_CC65 "$(command -v cc65)"
  write_export SIXIES_CA65 "$(command -v ca65)"
  write_export SIXIES_LD65 "$(command -v ld65)"
  write_export SIXIES_CL65 "$(command -v cl65)"
  write_export SIXIES_AR65 "$(command -v ar65)"
  write_export SIXIES_OD65 "$(command -v od65)"
  write_export SIXIES_SIM65 "$(command -v sim65)"
  write_export SIXIES_NES_EMULATOR "$(command -v nestopia)"
} > "$ENV_FILE"

{
  printf 'Sixies NES port root: %s\n' "$PORT_ROOT"
  printf 'NES plan: %s\n' "$ROOT_DIR/docs/porting-nes.md"
  printf 'cc65 version: %s\n' "${cc65_version:-unknown}"
  printf 'cc65 path: %s\n' "$(command -v cc65)"
  printf 'ca65 path: %s\n' "$(command -v ca65)"
  printf 'ld65 path: %s\n' "$(command -v ld65)"
  printf 'cl65 path: %s\n' "$(command -v cl65)"
  printf 'ar65 path: %s\n' "$(command -v ar65)"
  printf 'od65 path: %s\n' "$(command -v od65)"
  printf 'sim65 path: %s\n' "$(command -v sim65)"
  printf 'NES emulator path: %s\n' "$(command -v nestopia)"
  printf 'Environment exports: %s\n' "$ENV_FILE"
} > "$STATUS_FILE"

cat "$STATUS_FILE"
echo "NES toolchain setup complete. Source $ENV_FILE to load canonical paths in a shell."
