; Generated by scripts/convert-exclamations.py.
* = $ccb1
ExclamationSpriteData:
!bin "src/assets/exclamation_sprites.bin"
ExclamationDataLo:
!byte <(ExclamationSpriteData + 0),<(ExclamationSpriteData + 146),<(ExclamationSpriteData + 264),<(ExclamationSpriteData + 359),<(ExclamationSpriteData + 490),<(ExclamationSpriteData + 617)
ExclamationDataHi:
!byte >(ExclamationSpriteData + 0),>(ExclamationSpriteData + 146),>(ExclamationSpriteData + 264),>(ExclamationSpriteData + 359),>(ExclamationSpriteData + 490),>(ExclamationSpriteData + 617)
