; Generated by scripts/pack-koala.py.
GameOverKoalaBitmapLo:
!byte <(GameOverKoalaPacked + 0),<(GameOverKoalaPacked + 231),<(GameOverKoalaPacked + 1096),<(GameOverKoalaPacked + 2028),<(GameOverKoalaPacked + 2824)
GameOverKoalaBitmapHi:
!byte >(GameOverKoalaPacked + 0),>(GameOverKoalaPacked + 231),>(GameOverKoalaPacked + 1096),>(GameOverKoalaPacked + 2028),>(GameOverKoalaPacked + 2824)
GameOverKoalaScreenLo:
!byte <(GameOverKoalaPacked + 163),<(GameOverKoalaPacked + 887),<(GameOverKoalaPacked + 1836),<(GameOverKoalaPacked + 2645),<(GameOverKoalaPacked + 3004)
GameOverKoalaScreenHi:
!byte >(GameOverKoalaPacked + 163),>(GameOverKoalaPacked + 887),>(GameOverKoalaPacked + 1836),>(GameOverKoalaPacked + 2645),>(GameOverKoalaPacked + 3004)
GameOverKoalaColorLo:
!byte <(GameOverKoalaPacked + 217),<(GameOverKoalaPacked + 1039),<(GameOverKoalaPacked + 1992),<(GameOverKoalaPacked + 2790),<(GameOverKoalaPacked + 3030)
GameOverKoalaColorHi:
!byte >(GameOverKoalaPacked + 217),>(GameOverKoalaPacked + 1039),>(GameOverKoalaPacked + 1992),>(GameOverKoalaPacked + 2790),>(GameOverKoalaPacked + 3030)
GameOverKoalaBackground = $00
