; Generated by scripts/pack-koala.py.
GameOverKoalaBitmapLo:
!byte <(GameOverKoalaPacked + 0),<(GameOverKoalaPacked + 140),<(GameOverKoalaPacked + 950),<(GameOverKoalaPacked + 1814),<(GameOverKoalaPacked + 2674)
GameOverKoalaBitmapHi:
!byte >(GameOverKoalaPacked + 0),>(GameOverKoalaPacked + 140),>(GameOverKoalaPacked + 950),>(GameOverKoalaPacked + 1814),>(GameOverKoalaPacked + 2674)
GameOverKoalaScreenLo:
!byte <(GameOverKoalaPacked + 105),<(GameOverKoalaPacked + 753),<(GameOverKoalaPacked + 1601),<(GameOverKoalaPacked + 2456),<(GameOverKoalaPacked + 3061)
GameOverKoalaScreenHi:
!byte >(GameOverKoalaPacked + 105),>(GameOverKoalaPacked + 753),>(GameOverKoalaPacked + 1601),>(GameOverKoalaPacked + 2456),>(GameOverKoalaPacked + 3061)
GameOverKoalaColorLo:
!byte <(GameOverKoalaPacked + 127),<(GameOverKoalaPacked + 883),<(GameOverKoalaPacked + 1765),<(GameOverKoalaPacked + 2608),<(GameOverKoalaPacked + 3119)
GameOverKoalaColorHi:
!byte >(GameOverKoalaPacked + 127),>(GameOverKoalaPacked + 883),>(GameOverKoalaPacked + 1765),>(GameOverKoalaPacked + 2608),>(GameOverKoalaPacked + 3119)
GameOverKoalaBackground = $00
