; Generated by scripts/build-merge-callouts.py.
* = $3000
MergeCalloutPackedData:
!bin "src/assets/merge_callouts_packed.bin"
MergeCalloutOffsetLo: !byte $00,$38,$d9,$60,$8f,$f2,$aa,$ff,$b1,$37
MergeCalloutOffsetHi: !byte $00,$01,$02,$04,$05,$06,$08,$09,$0b,$0d
MergeCalloutGeneralCount = 8
MergeCalloutFivesIndex = 8
MergeCalloutSixiesIndex = 9
