; Generated by scripts/build-side-control-icons.py; do not edit.
; Overlapping-dice New Game icon derived from the supplied badge.
* = $5d80
NewGameSprite:
!byte $00,$e0,$00,$03,$e0,$00,$0f,$f0
!byte $00,$3f,$f8,$00,$3f,$f8,$00,$3f
!byte $7c,$00,$3f,$79,$c0,$3f,$f7,$f0
!byte $1f,$df,$b0,$1f,$bf,$f8,$1e,$77
!byte $f8,$0e,$76,$7c,$0e,$7e,$ec,$04
!byte $7f,$fc,$00,$7d,$f8,$00,$3d,$f0
!byte $00,$3f,$f8,$00,$1f,$f0,$00,$1f
!byte $c0,$00,$0e,$00,$00,$00,$00,$00
