; Generated by scripts/pack-koala.py.
TitleKoalaBitmapLo:
!byte <(TitleKoalaPacked + 0),<(TitleKoalaPacked + 620),<(TitleKoalaPacked + 1868),<(TitleKoalaPacked + 3102),<(TitleKoalaPacked + 4255)
TitleKoalaBitmapHi:
!byte >(TitleKoalaPacked + 0),>(TitleKoalaPacked + 620),>(TitleKoalaPacked + 1868),>(TitleKoalaPacked + 3102),>(TitleKoalaPacked + 4255)
TitleKoalaScreenLo:
!byte <(TitleKoalaPacked + 463),<(TitleKoalaPacked + 1543),<(TitleKoalaPacked + 2737),<(TitleKoalaPacked + 3941),<(TitleKoalaPacked + 4676)
TitleKoalaScreenHi:
!byte >(TitleKoalaPacked + 463),>(TitleKoalaPacked + 1543),>(TitleKoalaPacked + 2737),>(TitleKoalaPacked + 3941),>(TitleKoalaPacked + 4676)
TitleKoalaColorLo:
!byte <(TitleKoalaPacked + 567),<(TitleKoalaPacked + 1722),<(TitleKoalaPacked + 2928),<(TitleKoalaPacked + 4105),<(TitleKoalaPacked + 4772)
TitleKoalaColorHi:
!byte >(TitleKoalaPacked + 567),>(TitleKoalaPacked + 1722),>(TitleKoalaPacked + 2928),>(TitleKoalaPacked + 4105),>(TitleKoalaPacked + 4772)
TitleKoalaBackground = $00
